name: Test

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: "Server tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install FlatBuffers compiler
        run: sudo apt-get update && sudo apt-get install -y flatbuffers-compiler

      - name: Generate protocol modules
        run: yarn schema:generate

      - name: Run tests
        run: yarn test
